name: shartflix
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  inner_shadow_container: ^1.0.4

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.7

  # Networking
  dio: ^5.3.2
  http: ^1.1.0
  json_annotation: ^4.8.1

  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # UI & Navigation
  cached_network_image: ^3.3.0
  flutter_localizations:
    sdk: flutter

  # Utils
  logger: ^2.0.2+1
  get_it: ^7.6.4
  injectable: ^2.3.2
  dartz: ^0.10.1

  # Firebase
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.8

  # Icons
  flutter_svg: ^2.0.10+1

  # Image Picker
  image_picker: ^1.2.0

  # Animations
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1

  # App Icons
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: EuclidCircularA
      fonts:
        - asset: assets/fonts/Euclid Circular A Regular.ttf
          weight: 400
        - asset: assets/fonts/Euclid Circular A Medium.ttf
          weight: 500
        - asset: assets/fonts/Euclid Circular A SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Euclid Circular A Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900

# App Icons Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/SinFlixLogo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo/SinFlixLogo.png"
    background_color: "#1A1A1A"
    theme_color: "#FF3B30"
  windows:
    generate: true
    image_path: "assets/logo/SinFlixLogo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo/SinFlixLogo.png"
